name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: Remove-Item * -Recurse -Force -Confirm:$false -ErrorAction Ignore

      - uses: actions/checkout@v2
        with:
          path: SML

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Create UE directory
        run: mkdir ue

      - name: Download, Extract and Setup UE
        working-directory: ue
        run: |
          gh release download --repo satisfactorymodding/UnrealEngine -p "UnrealEngine-CSS-Editor-Win64.7z.*"
          7z x UnrealEngine-CSS-Editor-Win64.7z.001
          rm UnrealEngine-CSS-Editor-Win64.7z*
          .\\SetupScripts\\Register.bat

      - name: Download and Extract Wwise
        run: |
          Invoke-WebRequest -Uri "https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-windows.exe" -OutFile "b2.exe"
          .\b2.exe authorize-account "${{ secrets.WWISE_B2_KEY_ID }}" "${{ secrets.WWISE_B2_KEY }}"
          .\b2.exe download-file-by-name "${{ secrets.WWISE_B2_BUCKET }}" "Wwise.7z" "Wwise.7z"
          7z x Wwise.7z -oSML\\Plugins\\
          rm Wwise.7z

      - name: Generate VS project files
        run: .\\ue\\Engine\\Build\\BatchFiles\\Build.bat -projectfiles -project="$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" -game -rocket -progres

      - name: Build for Shipping
        run: MSBuild.exe .\\SML\\FactoryGame.sln /p:Configuration="Shipping" /p:Platform="Win64" /t:"Games\FactoryGame"

      - name: Build for Development Editor
        run: MSBuild.exe .\\SML\\FactoryGame.sln /p:Configuration="Development Editor" /p:Platform="Win64" /t:"Games\FactoryGame"

      - name: Package SML Mod
        run: .\\ue\\Engine\\Build\\BatchFiles\\RunUAT.bat -ScriptsForProject="$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" PackagePlugin -Project="$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" -dlcname=SML -build -clientconfig=Shipping -serverconfig=Shipping -platform=Win64 -nocompileeditor -installed

      - name: Archive SML artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' }}
        with:
          name: sml
          path: SML\\Saved\\ArchivedPlugins\\SML\\SML-Windows.zip
